# automatic testing with Travis CI!

language: javascript

before_script:
  - npm install tape --save-dev

script:
  - node test.js

notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: always
    on_failure: always
