# automatic testing with Travis CI!

language: javascript

before_script:
  - npm install tape --save-dev

script:
  - node test.js

notifications:
  email:
    on_success: change
    on_failure: always
